spiketools/measures/conversions.py
When working through some of the functions, we noticed and inconsistency in spike units. To help address this, this PR changes a specification about the unit of spike times.
What's added:
* changes unit description of spikes from seconds to milliseconds in function `create_spike_train`.
* adds milliseconds to the description of spikes in functions `convert_train_to_times` and `convert_isis_to_spikes`.
What's next:
* we still need to update the documentation of any other functions that assume milliseconds as the unit of spike.
=> [DOC] - Corrected units in documentation within conversions.py

spiketools/measures/conversions.py
Addressing #75 
There is an issue with the `create_spike_train` function, in that it sometimes ignores the last spike time. 
This affects `shuffle_circular` and `shuffle_bins` functions.
This seems to be happening because the pre-allocated space for the output (`spike_train`) in the `create_spike_train` is too small by one. Additionally, when setting `1` to the correct `spike_train` positions, the last one is missing.
What's changed:
* Pre-allocated space for the output (`spike_train`) in the `create_spike_train` is increased by one. 
* Last spike time included in `spike_train`.
=> [BUG] - Issue with `create_spike_train`

spiketools/stats/permutations.py
The functions in `stats/permutations.py` don't have examples in their docstrings yet.
What's added:
* Examples (in docstring) for `vec_perm`, `compute_empirical_pvalue`,  and `zscore_to_surrogates` functions.
=> [MNT] - Added examples to `stats/permutations.py`

spiketools/spatial/occupancy.py, spiketools/spatial/utils.py
Added 1d and 2d cases for functions within `spatial\occupancy.py` and `spatial\utils.py`.
The goal is to reduce unnecessary overlapping code.
Addressing #101.
Functions that changed:
* `compute_spatial_bin_edges`
* `compute_spatial_bin_assignment`
* `compute_occupancy` 
* `get_pos_ranges` (also added example/docstring test for this one)
=> [ENH] - 1d and 2d function compatibility

spiketools/stats/shuffle.py, spiketools/tests/conftest.py, spiketools/tests/measures/test_measures.py
Updating `shuffle_bins` to prevent broken case scenarios.
Addressing #107.
What's changed:
* Units: milliseconds -> seconds
* Argument default: `bin_width_range=[50, 2000]` -> `bin_width_range=[.5, 7]`
What's added:
* More description for `bin_width_range` argument in the Notes of the docstring.
* New spikes to `tspikes()` (`conftest.py`) due to the new maximum in `bin_width_range=[.5, 7]` default.
* New ISIs to `test_compute_isis(tspikes)` to accommodate new spikes in `tspikes`.
=> [ENH] - Update Shuffle Circular-Bins

spiketools/modutils/functions.py, spiketools/plts/spatial.py, spiketools/tests/modutils/test_functions.py, spiketools/tests/plts/test_spatial.py, spiketools/tests/plts/test_utils.py, spiketools/tests/tutils.py
This is a quick extension that adds a `plot_trial_heatmaps`, a helper function to plot heatmaps for individual trials, all together. 
It also adds some associated code to help with managing parameters and testing this kind of function.
=> [ENH] - Add `plot_trial_heatmaps` function

spiketools/spatial/place.py
This PR fixes an assignment bug in `compute_trial_place_bins` that stopped it working properly for 1d cases. 
@claire98han - this relates to the discussion we had today. I ended up needing to use the function for 1d cases, so I'm pushing through this quick fix now, to get it working! Otherwise, the rest of the related points I'll leave to you!
=> [BIG] - Fix assignment in compute_trial_place_bins

spiketools/spatial/occupancy.py, spiketools/spatial/place.py, spiketools/tests/spatial/test_occupancy.py, spiketools/tests/utils/test_data.py, spiketools/utils/checks.py, spiketools/utils/data.py
This PR addresses some quirks with doing spatial binning and occupancy calculations if using an `area_range` that does not extend across the whole position range. If doing so (sub-selecting a range to look at), previously there were a bunch of warnings that could go a bit over the top - but as long as one intends to choose an area smaller than the whole field, that should be valid, so this fixes things up to do so more smoothly.
=> [ENH] - Fix up management of edges checks & warnings

spiketools/spatial/place.py
This PR fixed `compute_trial_place_bins` by adding `check_position_bins` for cases using 1d spatial bins. 
@TomDonoghue - This is another quick fix for the function. I'll add the test functions and examples in the documentation once it's merged.
=> add check_position_bins

spiketools/stats/anova.py, spiketools/tests/stats/test_anova.py
This PR extends bin df creation to accept extra data columns. This can be useful when adding additional trial-level information to dataframes (for example, for splitter cell analyses in T3).
=> [ENH] - Update `create_dataframe_bins`

doc/api.rst, spiketools/stats/shuffle.py, spiketools/tests/stats/test_shuffle.py, spiketools/tests/utils/test_extract.py, spiketools/utils/extract.py
This PR add functionality for dealing with 'gaps' in spike times (for example, if an amp was turned off for some time in the middle of an experiment), and in particular a strategy to dealing with this when shuffling spike times. 
It adds:
- utility functions for dropping out / adding back in 'gap' time range(s)
- a strategy for shuffling by dropping out a gap, shuffling, and then re-inserting the gap(s)
=> [ENH] - Add functionality for dealing with gaps

doc/api.rst, spiketools/tests/utils/test_trials.py, spiketools/utils/trials.py
This PR adds a `utils.trials` file for utility functions for managing trial-level data. 
It adds some split functions, that are convenience functions for splitting up trials by a list of condition labels. This added for trials organized as lists of lists (eg. spike times) and for trials organized in an array (eg. firing rate across bins per trial).
=> [ENH] - Add utils for working with trial level data

spiketools/plts/spatial.py, spiketools/plts/utils.py, spiketools/tests/plts/test_utils.py
This PR adds a helper function for inverting plot axes, and then links this in to the spatial plots, allowing for directly controlling the plot orientation for spatial plots. 
Note that in these cases, inverting plot axes is functionally equivalent to flipping a 2d data (where flipping the 2d array up/down is the same as inverting the y axis, and flipping a 2d array left/right is equivalent to inverting the x axis).
Note: this addition stems from a discussion (with @maestapereira, I think) about adding helper utilities for flipping position plot orientations, since sometimes the original orientation of the position data isn't the same as how we want to plot it.
=> [ENH] - Add axis inverting helper function and apply to spatial plots

doc/api.rst, spiketools/plts/spatial.py, spiketools/spatial/occupancy.py, spiketools/spatial/place.py, spiketools/spatial/utils.py, spiketools/tests/spatial/test_occupancy.py, spiketools/tests/spatial/test_utils.py, spiketools/tests/utils/test_checks.py, spiketools/tests/utils/test_data.py, spiketools/tests/utils/test_epoch.py, spiketools/tests/utils/test_extract.py, spiketools/tests/utils/test_trials.py, spiketools/utils/checks.py, spiketools/utils/data.py, spiketools/utils/epoch.py, spiketools/utils/extract.py, spiketools/utils/trials.py
This relates to #141 - and sweeps through procedures that can work on row / column arrays (both general utilities and space-specific functionality), and works through things to allow them to support either row or column organized 2d arrays. 
The general strategy is to try and infer the orientation of the data, and work from there, meaning that these functions should still work as expected (no extra arguments) on row data, but should also work if the data is column organized. This should maintain backwards compatibility, while supporting columnar data, including supporting position data organized in columns. 
In practice, this means that passing in row position data should still work just as it does currently, but also that passing in column-oriented data should work, and provide the same …
=> [ENH] - Update 1d vs 2d (rows & columns) support for array utilities

doc/api.rst, spiketools/measures/collections.py, spiketools/measures/conversions.py, spiketools/measures/spikes.py, spiketools/measures/trials.py, spiketools/tests/measures/test_collections.py, spiketools/tests/measures/test_conversions.py, spiketools/tests/measures/test_spikes.py, spiketools/tests/measures/test_trials.py, spiketools/tests/utils/test_checks.py, spiketools/tests/utils/test_timestamps.py, spiketools/utils/checks.py, spiketools/utils/timestamps.py
Responds to #150, plus some related extensions.
This PR re-organizes and extends some of the functionality related to compute continuous firing rates. Related to the original point, it adds the `create_bin_times` function to define the timestamps related to a time definition, and computes and returns these from `compute_trial_frs`, so they are available and can be used for plotting. 
Additional updates:
- adds the `compute_presence_ratio` function
- refactors convert functions to split out converting to counts vs converting to frs
=> [ENH] - Time bins & time definitions for binned spike counts

doc/api.rst, spiketools/measures/spikes.py, spiketools/measures/trials.py, spiketools/spatial/place.py, spiketools/tests/utils/test_extract.py, spiketools/tests/utils/test_timestamps.py, spiketools/utils/epoch.py, spiketools/utils/extract.py, spiketools/utils/timestamps.py
This is a collection of updates, including:
- adding the `sum_time_ranges` helper function
- updates some management of selecting time_ranges to compute measures across
- some updates to doctests (trying to simplify)
- update to inclusiveness of time range selection**
**this is the most important update. Previously, we did all time selection with inclusive starts and ends, which seems nice (selecting [2, 4] from [1.2, 2.0, 3.1, 4.0] would return [2.0, 4.0]) - but this can lead to some problems, most notably, if we do something like stepwise segment extraction, we can select the same value twice (eg., the value 4.0 would be selected for both time ranges [2, 4] and for [4, 6]). To avoid this problem, this update makes all time range selections inclusive start, exclusive end (so - values >= …
=> [ENH/MNT] - Miscellaneous updates / fixes

spiketools/plts/task.py
Fixes an issue with `plot_task_structure` in which the plot could fail with an uninformative error. 
The error turns out to be line inputs in arrays - since the underlying annotate function assumes a list. 
@weijiazh97 - this should fix the train issue (https://github.com/HSUPipeline/AnalyzeTrain/issues/2)
=> [MNT] - Fix plot_task_structure

MANIFEST.in, Makefile, setup.py, spiketools/tests/tsettings.py
Updates:
- use `build` for distributions (see https://github.com/fooof-tools/fooof/pull/282/)
- drop use of `package_resources` (see https://github.com/fooof-tools/fooof/pull/281)
=> [MNT] - Build & install related updates

spiketools/tests/utils/test_base.py, spiketools/utils/base.py
The `listify` function would end up flattening multi-dimensional arrays, which was unintended, and broke things like proper plotting in `plot_positions`. This fixes the `listify` function for explicitly handling multi-dimensional arrays, also fixing downstream effects.
=> [BUG] - Fix listify for multi-d arrays

doc/api.rst, spiketools/stats/permutations.py, spiketools/stats/shuffle.py, spiketools/tests/stats/test_permutations.py, spiketools/tests/stats/test_shuffle.py, spiketools/tests/utils/test_data.py, spiketools/utils/data.py, tutorials/plot_stats.py
Updates to the shuffle Poisson approach:
Mainly, it responds to #163, making the Poisson shuffle approach regenerate a new set of Poisson generated spikes per 'shuffle'. This fixes the previous issue of simply permuting a single shuffle. However, since the Poisson generation is not guaranteed to return the same number of spikes, this means that this approach now returns a list of shuffles, each array within the list which can have somewhat different length. 
Because the shuffle poisson doesn't return a uniform array like the other function, I also removed it from being an option in the `shuffle_spikes` function. I think this is consistent with us not really recommending this approach (not to mention that it's not a "shuffling" function in the sense that spikes are not shuffled, but rather …
=> [MNT] - Update shuffle poisson approach

spiketools/spatial/occupancy.py, spiketools/tests/spatial/test_occupancy.py, tutorials/plot_spatial.py
Responds to #179 
Previously, it was sort of confusing the `speed_threshold` was a MINIMUM value, but `time_threshold` was a MAXIMUM value, and also, this scheme only allowed for a subset of thresholding one might want to do (not allowing, for example, for dropping entries with too short a time duration. 
This PR therefor updates speed & time threshold to use explicit `min_x` and `max_x` threshold values for both, which I think is probably better. 
The only sorta annoying thing is that this is a breaking change (changes the argument names), so some older code will need to be updated. Any thoughts on this are welcome!
=> [MNT] - Update thresholds in occupancy calculations

spiketools/plts/spatial.py, spiketools/spatial/distance.py, spiketools/spatial/occupancy.py, spiketools/spatial/place.py, spiketools/spatial/utils.py, spiketools/tests/spatial/test_utils.py, spiketools/tests/utils/test_checks.py, spiketools/tests/utils/test_data.py, spiketools/utils/checks.py, spiketools/utils/data.py
Responds to #162 
The key issue was that because the infer the orientation of the data from the array shape / size (by assuming the # samples dimension > # values per sample), we get it wrong for this does not hold (for example, a single sample of 2D data, where the # samples < # values per sample). 
To improve our performance on this, we can use the fact that we often do know how many values per sample we expect - and so we can use that info (knowing we expected 2 values per sample allows us to make the correct call for shapes of (2, 1) or (1, 2). This update implements that and applies it across relevant places. 
I believe this effectively fixes at least most of the orientation inference, including the specific issue noted in #162, and also any situations in which position values are …
=> [MNT] - Update management of position orientation inference for ambiguous cases

spiketools/stats/generators.py, spiketools/tests/sim/test_times.py, spiketools/tests/stats/test_generators.py
Previously the `start_time` input to the poisson generator wasn't used properly - it would basically change the range of the values rather than properly defining the time range to simulate over (e.g. duration=2, start_time=1 would sim from range [1, 2] instead of [1,3], and duration=2, start_time=-2 would sim [-2, 2] instead of [-2, 0]). This update fixes that, and adds additional related tests.
=> [BUG] - Fix use of start_time in generator & sim func

doc/api.rst, spiketools/sim/__init__.py, spiketools/sim/times.py, spiketools/sim/train.py, spiketools/sim/trials.py, spiketools/tests/sim/test_trials.py
Adds functionality to directly simulate data organized into trials. 
We already had the same motif to do this in the tutorials, and it seemed right to be made into a function. There is basically one actually simulating function (based on simulated spike times from a poisson distribution), with the overall organization organized to mimic other sim functions (that will hopefully also allow for extending to supporting other approaches for simulating trials.
=> [ENH] - Add functionality to simulate trials

spiketools/measures/conversions.py, spiketools/stats/shuffle.py, spiketools/tests/conftest.py, spiketools/tests/measures/test_conversions.py, spiketools/tests/measures/test_spikes.py, spiketools/tests/stats/test_shuffle.py
Several conversion and shuffle function basically assume that the time range of a set of spike times is something like [0, end_time]. This creates an issue if you want to use these functions with a set of spike times that is not like this, and is instead [start_time, end_time], whereby start_time could be a positive or negative number. 
This PR updates conversion and shuffle functions to support such a case. 
For example, given the following set of spike times:
```
tspikes [-1.5, -0.5, 0.75, 1.1, 1.5]
```
Previously, the spike train conversion for this would not be correct (it would end up length 1.5 seconds instead of 3), and relatedly, shuffling wouldn't work properly. By updating some data checks to check for ranges that might not start at time 0, and adding either a `time_range` or …
=> [ENH] - Update conversions and shuffles to support non-zero start time

spiketools/measures/conversions.py, spiketools/tests/conftest.py, spiketools/tests/measures/test_conversions.py, spiketools/tests/stats/test_shuffle.py
This fixes a bug related to #191, where we added support for conversions and shuffles with non-zero start times. 
The issue is that I added tests for negative start times, but not start time offsets > 0, with the bug being that due to the length check in `convert_times_to_train`, this could lead to spikes getting cut off, and so not properly encoding the spike train (which could also lead to failures in shuffling). 
This update fixes that - making sure the times -> train procedure tracks the length of the spike times considering the spike time cut off, rather than erroneously cutting off (for example, previously a spike range between 5-15, with length 10, would cut of spike times after time value 10). 
The actual fix here is a small change to the convert function - the rest of the PR is …
=> [BUG] - Fix converting times -> train with positive start time offset

doc/api.rst, spiketools/spatial/occupancy.py, spiketools/spatial/place.py, spiketools/tests/spatial/test_place.py, spiketools/tests/utils/test_extract.py, spiketools/utils/data.py, spiketools/utils/epoch.py, spiketools/utils/extract.py
In #185 we updated how the different thresholds get used when computing occupancy. 
What I forgot to do / check was to do the analogous updates for computing place bins (the neural part), meaning that currently defining behavioural occupancy and place-related neural firing could be different. 
This PR updates place computations to use thresholds consistent to occupancy. In doing so, it also does some updates and additions to related utils.
=> [MNT] - Update computing place measures for thresholding

doc/api.rst, spiketools/plts/trials.py, spiketools/plts/utils.py, spiketools/tests/plts/test_trials.py, spiketools/tests/utils/test_trials.py, spiketools/utils/trials.py
This extends trial related plotting functionality, most notably:
- allow `plot_rasters` and `plot_rate_by_time` to accept dictionary input (convenient for multiple conditions)
- add new `plot_raster_and_rates` to plot a multi-axis, aligned plot of the raster and continuous firing rates
An example of the `plot_raster_and_rates` looks like this:
=> [ENH] - Extend trial plotting

spiketools/measures/collections.py, spiketools/measures/spikes.py, spiketools/measures/trials.py, spiketools/spatial/distance.py, spiketools/spatial/utils.py, spiketools/stats/anova.py, spiketools/stats/trials.py, spiketools/utils/data.py, spiketools/utils/epoch.py, spiketools/utils/extract.py
There is a change in numpy >= 2.0 in how values are printed out (it now prints the type). This creates some issues with doctests (e.g. expected value 1.0 is now expected value np.float64(1.0)). 
There does not seem to be a clear way to address this, that works across numpy 1.X and 2.X. For now at least, this PR adds some adhoc fixes - typecasting some values to fix it up, and turning some doctest checks off.
=> [WIP] - Update doctests for change in numpy
