spiketools/spiketools

README.rst

[DOC] - Update README

---

spiketools/sim/utils.py
spiketools/tests/sim/test_utils.py

[ENH] - Added Test Function for `test_refractory`

---

spiketools/stats/shuffle.py
spiketools/tests/conftest.py
spiketools/tests/measures/test_conversions.py
spiketools/tests/measures/test_measures.py
spiketools/tests/plts/test_data.py
spiketools/tests/plts/test_spikes.py
spiketools/tests/plts/test_stats.py
spiketools/tests/sim/test_dist.py
spiketools/tests/sim/test_prob.py
spiketools/tests/spatial/test_information.py
spiketools/tests/spatial/test_occupancy.py
spiketools/tests/spatial/test_utils.py
spiketools/tests/stats/test_generators.py
spiketools/tests/stats/test_permutations.py
spiketools/tests/stats/test_shuffle.py
spiketools/tests/tsettings.py
spiketools/tests/utils/test_checks.py

[MNT] - Check & Updates Tests

---

doc/api.rst
spiketools/plts/data.py
spiketools/plts/trials.py
spiketools/tests/plts/test_data.py

[ENH] - Plot updates

---

tutorials/plot_sims.py

In the process of creating tutorials with plots demonstrating potential uses of functions. This one primarily covers the spiketools.sims module. Related to #32
What's added:
First draft of tutorial for sims(dist.py, prob.py, utils.py).

[DOC] - Added tutorial for `spiketools.sims`

---

doc/api.rst
spiketools/plts/spikes.py
spiketools/tests/plts/test_spikes.py

This PR extends some plotting, adding:
- plot_waveforms3d
- plot_spikehist2d

[WIP/ENH] - Extend plotting

---

doc/api.rst
spiketools/measures/circular.py
spiketools/plts/data.py
spiketools/tests/measures/test_circular.py
spiketools/tests/plts/test_data.py

Additions:
- `measures/circular/bin_circular`
- `plts/data/plot_polar_hist`

[ENH] - Add circular data related functions

---

spiketools/measures/conversions.py
spiketools/objects/cell.py
spiketools/spatial/occupancy.py
spiketools/stats/generators.py
spiketools/stats/shuffle.py
spiketools/tests/conftest.py
spiketools/tests/measures/test_conversions.py
spiketools/tests/measures/test_measures.py
spiketools/tests/plts/test_trials.py
spiketools/tests/spatial/test_occupancy.py
spiketools/tests/stats/test_shuffle.py
spiketools/tests/utils/test_checks.py
spiketools/utils/checks.py
spiketools/utils/data.py

This PR updates spiketools to default to and work with spike times in seconds.
Relates to #11 & #12

[DEV] - Update time

---

spiketools/plts/space.py
spiketools/tests/plts/test_space.py

[ENH] - Plot updates: support trial data in plot_positions

---

doc/api.rst
spiketools/plts/annotate.py
spiketools/plts/data.py
spiketools/plts/settings.py
spiketools/plts/space.py
spiketools/tests/plts/test_annotate.py
spiketools/tests/plts/test_data.py
spiketools/tests/plts/test_space.py

[ENH] - Plot updates / extensions

---

.github/workflows/build.yml
doc/api.rst
optional-requirements.txt
spiketools/modutils/dependencies.py
spiketools/plts/annotate.py
spiketools/spatial/occupancy.py
spiketools/spatial/utils.py
spiketools/stats/anova.py
spiketools/stats/permutations.py
spiketools/tests/conftest.py
spiketools/tests/modutils/test_dependencies.py
spiketools/tests/plts/test_annotate.py
spiketools/tests/spatial/test_occupancy.py
spiketools/tests/stats/test_anova.py
spiketools/tests/stats/test_permutations.py
spiketools/tests/utils/test_data.py
spiketools/utils/data.py

This PR adds some helper functions for doing ANOVA analyses + miscellaneous related functions. 
Some of the original code of these updates was developed by @claire98han ([here](https://github.com/JacobsSU/AnalyzeTH/pull/4)).
This code was then refactored, as part of [these updates](https://github.com/JacobsSU/AnalyzeTH/pull/5).
@claire98han - do you want to have a quick look through things here, and check that everything makes sense based on your work on running ANOVAs? 
You can look [here](https://github.com/JacobsSU/AnalyzeTH/pull/5) to see how these functions get used in the refactored code. Since this code has been tested in updating TH analyses, I don't think it needs too much stress-testing here, and is hopefully about good to go.

[ENH] - Add helper functions for doing ANOVAs + misc extras

---

doc/api.rst
spiketools/sim/times.py
spiketools/sim/train.py
spiketools/sim/utils.py
spiketools/stats/generators.py
spiketools/stats/shuffle.py
spiketools/tests/sim/test_times.py
spiketools/tests/sim/test_train.py
spiketools/tests/sim/test_utils.py
spiketools/tests/stats/test_generators.py

This re-organizes and updates the simulation functions. In particular, it extends the new organization whereby we organize functions by what they simulate (spike times vs spike trains) as opposed to organizing them by how they do it. 
@claire98han & @maestapereira - another one to give a quick check to, to see if it all makes sense, etc.

[MNT] - Update and extend simulation functions

---

doc/api.rst
spiketools/plts/__init__.py
spiketools/plts/annotate.py
spiketools/plts/data.py
spiketools/plts/spatial.py
spiketools/plts/spikes.py
spiketools/plts/task.py
spiketools/plts/trials.py
spiketools/plts/utils.py
spiketools/stats/shuffle.py
spiketools/tests/plts/test_annotate.py
spiketools/tests/plts/test_data.py
spiketools/tests/plts/test_spikes.py

This cleans up & extends some plotting things. Responds to #84
There are some name & organizational changes in here, namely that:
- `plot_spikehist2d` -> `plot_waveform_density`
- `shade` is now used specifically for error shading, and `vshade` is used for shading vertical columns
- the plot waveforms functions now have a consistent usage of a `times` vector

[ENH] - Update and extend plotting

---

doc/glossary.rst

Related to a point in #10 - this checks and updates the glossary.

[DOC] - Update glossary

---

tutorials/plot_stats.py

This PR contains reviews and updates before spiketools 0.1 release. 
What's updated: 
- Added tutorial for ANOVA

Updates before release

---

spiketools/stats/anova.py
tutorials/plot_measures.py
tutorials/plot_sims.py
tutorials/plot_spatial.py
tutorials/plot_stats.py

In general, updated tutorials to reflect changes after last PRs (#123 through #126) (i.e.: function name changes, new functions, etc).
Also double checked to see that capitalization and layout was consistent across tutorials.<br>
What's changed:
* `plot_measures.py`: swapped the order of two items : *Convert spiking data* (was 2, became 1) with *Compute measures of spiking activity* (was 1, became 2). The reason for the swap is to remove redundancy, since we use both spike times and spike train (calculated in the *Convert spiking data*) in *Compute measures of spiking activity*.
* `plot_measures.py`: the firing rate of the first example (it was around 500 Hz) to 100 Hz (I left it high because of the spike train/spike times example).
* `plot_spatial.py`: the x position array (to better …

[DOC] - Update tutorials for codebase updates

---

spiketools/plts/style.py
spiketools/tests/plts/test_style.py
spiketools/tests/utils/test_checks.py
spiketools/utils/checks.py

This is a quick / small update to add some helper utilities for styling plots.

[ENH] - Add some helper functionality for plot styling

---

doc/api.rst
spiketools/tests/utils/test_base.py
spiketools/utils/base.py

Adds some utility functions for working with dictionaries.

[ENH] - Add dict util funcs

---

doc/api.rst
spiketools/plts/annotate.py
spiketools/plts/spatial.py
spiketools/plts/spikes.py
spiketools/plts/stats.py
spiketools/plts/style.py
spiketools/plts/task.py
spiketools/plts/trials.py
spiketools/plts/utils.py
spiketools/tests/plts/test_annotate.py
spiketools/tests/plts/test_style.py
spiketools/tests/plts/test_utils.py

Minor updates of plot functions:
- Updates the shader annotate functions to accept multiple shade regions
- Updates style functions (drop_spines, invert_axes) to have the same API order as annotate functions
- Moves around some plot utilities and style functions

[MNT] - Update plot functions

---

tutorials/plot_measures.py
tutorials/plot_spatial.py
tutorials/plot_stats.py

Fixes to tutorials `plot_measures.py`, `plot_spatial.py`, and `plot_stats.py` to address #159 
All typos and suggestions are incorporated, except for item 7, which was moved to its own issue #163

[ENH] - Tutorial fixes

---

doc/api.rst
spiketools/plts/annotate.py
spiketools/plts/spatial.py
spiketools/plts/style.py
spiketools/spatial/checks.py
spiketools/tests/plts/test_annotate.py
spiketools/tests/plts/test_spatial.py
spiketools/tests/plts/test_style.py
spiketools/tests/utils/test_base.py
spiketools/utils/base.py

Responds to #165 
Updates plot functions, in particular adding better support for 1d position data, including:
- updating `plot_position_by_time` to support more annotation inputs (bin lines and event markers)
- add new plot `plot_position_1d`, for plotting 1d position data with overlaid
- miscellaneous updates, updating helper / utility functions and updating plot annotations

[ENH] - Position plot updates, including for 1D

---

README.rst
setup.py

adds statsmodels as an optional dependency
closes #173

adds statsmodels to extra reqs

---

doc/conf.py

adds binder config to sphinx config
closes #174

adds binder config to conf.py

---

doc/api.rst
spiketools/spatial/checks.py
spiketools/spatial/occupancy.py
spiketools/spatial/place.py
spiketools/spatial/position.py
spiketools/spatial/target.py
spiketools/spatial/utils.py
spiketools/tests/spatial/test_checks.py
spiketools/tests/spatial/test_position.py
spiketools/tests/spatial/test_utils.py
spiketools/tests/utils/test_timestamps.py
spiketools/utils/timestamps.py

A series of updates related to `spiketools.spatial.position` and associated code, including:
- update functions to have option to match time sampling of inputs
- updates of the docstring examples, for simplicity
- updates and organizations of helper check & utility functions

[MNT] - Updates & fixes related to position measures

---

doc/api.rst
spiketools/plts/task.py
spiketools/plts/trials.py
spiketools/spatial/checks.py
spiketools/tests/plts/test_task.py
spiketools/tests/spatial/test_checks.py
spiketools/tests/utils/test_checks.py
spiketools/tests/utils/test_epoch.py
spiketools/tests/utils/test_extract.py
spiketools/utils/checks.py
spiketools/utils/extract.py
spiketools/utils/trials.py

This is a set of miscellaneous updates (that stem for doing a sweep of usage in the T3 project). 
Updates include:
- adding and using a `check_param_type` helper function
- updating `plot_rate_by_time` to support a single 2d array that will be averaged
- add `plot_task_events` plot function
- adding some safety checking to `extract` functions

[MNT] - Miscellaneous updates

---

doc/api.rst
spiketools/plts/spatial.py
spiketools/plts/task.py
spiketools/tests/utils/test_base.py
spiketools/utils/base.py

Responds to #169 
This PR updates plot related code to fix some quirks as listed in the issue. 
In doing so, it adds some extra helper utility functions that get used in management.

[MNT] - Updates to utils & plots

---

doc/api.rst
spiketools/spatial/distance.py
spiketools/spatial/position.py
spiketools/spatial/speed.py
spiketools/tests/spatial/test_distance.py
spiketools/tests/spatial/test_position.py
spiketools/tests/spatial/test_speed.py
spiketools/tests/utils/test_extract.py
spiketools/utils/extract.py

This started as a response to #170, but then extended somewhat to now include:
- addition of extra extract functions that relate to #170 
- the addition of additional functions related to distance that might be useful
- update the API for functions that were in `spatial.position`
- these were previously the only functions that took in x & y positions: they now take the standard `position` array
- re-organize some files in spatial
- since most of the `position` file functions were distance related, rename this to `distance`
- because `speed` is a different measures, move this to it's own file
With some movements and new functions, double checking the naming of things here would be good (I'm not sold on all the names). Also, any thoughts on organization are welcome - I don't, for example, …

[MNT] - Updates & extensions to distance related functions (& extras)

---

tutorials/plot_spatial.py

In #177 we updated the approach for the distance functions and some related utilities, but that PR did not fix the tutorials for those changes. This PR updates the tutorials to work with the new approaches.

[DOC] - Fix / Update tutorial for update position / distance code

---

spiketools/plts/data.py
spiketools/plts/spatial.py
spiketools/plts/task.py
spiketools/plts/trials.py

Includes:
- aesthetic updates to `plot_rate_by_time`

[MNT] - Minor plot updates
